export const countries = [
    {name: "England" , code:"england"},
    {name: "Scotland" , code:"scotland"},
    {name: "Wales" , code:"wales"},
    {name:"Ireland", code: "IR"},
    {name:"Argentina", code:"AR"},
    {name:"Armenia", code:"AR"},
    {name: "Australia" , code:"AU"},
     {name: "Autria" , code:"AT"},
     {name: "Belarus" , code:"BY"},
    {name:"Belgium", code: "BE"},
    {name: "Bosnia and Herzegovia" , code:"BA"},
    {name: "Brazil" , code:"BR"},
    {name:"Bulgaria", code: "BG"},
    {name:"Canada", code:"CA"},
    {name: "China" , code:"CN"},
    {name:"Colombia", code: "CO"},
    {name:"Costa Rica", code:"CR"},
    {name:"Crotia", code:"HR"},
    {name: "Cuba" , code:"CU"},
    {name:"Czechia", code: "CZ"},
    {name:"Denmark", code:"DK"},
    {name: "Dominican Republic" , code:"DO"},
    {name:"Ecuador", code: "EV"},
    {name:"Egypt", code:"EG"},
    {name: "El Salvador" , code:"SV"},
    {name:"Estonia", code: "EE"},
    {name:"Fiji", code:"FJ"},
    {name: "Finland" , code:"FI"},
    {name:"France", code: "FR"},
    {name:"Georgia", code:"GE"},
    {name:"Germany", code:"DE"},
    {name: "Greece" , code:"GR"},
    {name:"Hungary", code: "HU"},
    {name:"Iceland", code:"IS"},
    {name:"India", code: "IN"},
    {name:"Israel", code:"IL"},
    {name: "Italy" , code:"IT"},
    {name:"Japan", code: "JP"},
    {name:"Korea", code:"KR"},
    {name:"Lithuania", code:"LT"},
    {name: "Luxembourg" , code:"LU"},
    {name:"Mexico", code: "HMX"},
    {name:"Moldova", code:"MD"},
    {name: "Monaco" , code:"MC"},
    {name:"Montenegro", code: "ME"},
    {name:"Morocco", code:"MA"},
    {name:"Netherlands", code:"NL"},
    {name: "New Zealand" , code:"NZ"},
    {name:"Norway", code: "NO"},
    {name:"Poland", code:"PL"},
    {name: "Portugal" , code:"PT"},
    {name:"Romania", code: "RO"},
    {name:"Russia", code:"RU"},
    {name:"Serbia", code:"PL"},
    {name: "Singapore" , code:"SG"},
    {name:"South Africa", code: "ZA"},
    {name:"Spain", code:"ES"},
    {name: "Sweden" , code:"SE"},
    {name:"Switzerland", code: "CH"},
    {name:"Taiwan", code:"TW"},
    {name: "Turkey" , code:"TR"},
    {name:"Ukraine", code: "UA"},
    {name:"UK", code:"GB"},
    {name:"USA", code:"US"},
    {name:"Zimababwe", code:"ZW"},

]
   
